spring.application.name=MarketDemo

spring.datasource.url=jdbc:mysql://localhost:3306/second_hand_market?characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver